add the IPFILTERING_FORBIDDEN response template
gravitee-io/gravitee-policy-ipfiltering pull request #35
Opened 2022-04-05 18:56 UTC by yurkovandrey

**Issue**

https://github.com/gravitee-io/issues/issues/6091

**Description**

add the **IPFILTERING_FORBIDDEN** response template to override the default responses provided by the ipfiltering policy

**Additional context**

I've tested the changes with the graviteeio/apim-gateway:3.15.3 docker image

2022-04-06 07:06 UTC, gaetanmaisse commented
Thanks for the contribution @yurkovandrey, we will review it soon! 
In the meantime can you reword your commit to follow the conventional commit format? 🙏🏻

2022-04-06 07:48 UTC, yurkovandrey commented
> Thanks for the contribution @yurkovandrey, we will review it soon!
> In the meantime can you reword your commit to follow the conventional commit format? 🙏🏻

Оh, I'm sorry for my inattention. I've read contributing.adoc, but didn't find any requirements for a commit format. Could you tell me where I can read about this?

2022-04-06 12:20 UTC, gaetanmaisse commented
@yurkovandrey ahah no problem, it's on us 🙈 , we forgot to update the contributing guide after the setup of semantic release. I've added it in my todo.

2022-05-10 06:23 UTC, marcambier requested changes

2022-05-10 06:23 UTC, marcambier commented on src/main/java/io/gravitee/policy/ipfiltering/IPFilteringPolicy.java
> +                Maps.<String, Object>builder().put("address", remoteAddress).build()
If we need to use remote address in response template, it's already available using `{#request.remoteAddress}`.
So maybe there is no need to add extra parameter here.
Could we remove it ?

2023-02-13 13:55 UTC, gaetanmaisse commented
Closing as it didn't get any update for a while

2023-02-13 13:55 UTC, closed without merging